[최원경] Assignment 1: Express API -초기 환경 세팅
wecode-bootcamp-korea/42-backend-westagram-3 pull request #2
Opened 2023-01-19 08:21 UTC by wkc28

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 추후  westagram 프로젝트를 진행하기 위한 초기 환경 세팅 , 향후 작업할 
빈 데이터베이스 구축

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 및 데이터베이스 정상 연동메세지 확인.
- mysql을 이용해 생성한 데이터베이스 확인

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. [Postman(Client]([url](<img width="709" alt="스크린샷 2023-01-19 오후 5 14 51" src="https://user-images.githubusercontent.com/121370410/213389493-2b3efb3a-b433-4a13-9890-c0b64b5bff6a.png">)) Tool)을 이용한 API 테스트 결과 이미지
3. 데이터베이스 구축 및 확인. 
<img width="204" alt="스크린샷 2023-01-19 오후 5 17 29" src="https://user-images.githubusercontent.com/121370410/213390132-30d11bea-5b50-47b9-914e-63e0db8372fd.png">

)
5. 

<br />

## :: 기타 질문 및 특이 사항
- 처음해보는 깃헙과정이 조금 험난했습니다. 
- 41행  코드중  (`server is listening on ${PORT}` )); 부분의 ``과 ''의 차이를 명확히 알고싶습니다.

2023-01-20 01:25 UTC, SeongJoon-K reviewed
안녕하세요 원경님!
피드백 확인 후 코드 수정하시고 `멘토 리뷰 요청` 으로 라벨을 변경해 주세요!

2023-01-20 01:25 UTC, SeongJoon-K commented on wonkyung/.env.sample
> +.enc
원경님 ! 파일 네이밍이 잘못되었습니다 `.env`로 수정해 주세요 !

2023-01-20 01:25 UTC, SeongJoon-K commented on wonkyung/.env.sample
> +node_moduels/
npm 패키지를 install 할 때 생기는 디렉토리는 `node_modules`입니다 !
확인 해서 다시 수정해 주세요!

2023-01-20 01:25 UTC, SeongJoon-K commented on wonkyung/app.js
> +const http = require("http");
`http` 는 node.js 런타임에서 제공하는 내장 모듈입니다.
위스타그램 API 구현 과제에서는 `express` 를 사용하여 서버를 구동시키고 있습니다.
해당 모듈은 사용하지 않기 때문에 코드는 삭제 해 주세요!

2023-01-20 01:25 UTC, SeongJoon-K commented on wonkyung/app.js
> +dotenv.config();
```suggestion
require("dotenv").config();

const express = require("express");
const cors = require("cors");
const morgan = require("morgan");

```

2023-01-20 01:25 UTC, SeongJoon-K commented on wonkyung/app.js
> +  });
- myDataSource 보다는 `appDataSource` , `mysqlDataSource` 혹은 간결하게 `database`로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.
- 추가로 `DataSource.initialize()` 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.

2023-01-20 01:25 UTC, SeongJoon-K commented on wonkyung/app.js
> +const server = http.createServer(app)
위에 말씀 드렸다시피 http 모듈은 더이상 사용하지 않기 때문에 해당 코드는 제거해 주세요!

2023-01-20 01:25 UTC, SeongJoon-K commented on wonkyung/app.js
> +}
express 객체를 app 이라는 객체로 받아서 사용하기 때문에 서버를 작동시키는 함수를 아래와 같이 수정해 주세요!
```suggestion
const start = async () =>{
   app.listen(PORT, () => console.log(`server is listening on ${PORT}` ));
}
```

2023-01-20 01:25 UTC, SeongJoon-K commented on wonkyung/package.json
> +  },
devDepecdency의 경우 개발시 사용되는 패키지를 정의합니다. express에 경우 개발이 아닌 프로젝트 전체에 사용되는 패키지이기 때문에 이를 dependency에 포함되게 수정해주세요

```
$ npm uninstall express
$ npm install express
```

2023-01-20 06:39 UTC, wkc28 commented on wonkyung/package.json
> +  },
요청사항 수정완료했습니다!

2023-01-20 08:07 UTC, SeongJoon-K reviewed
원경님 너무 고생하셨습니다 ~ ! require 순서만 변경해 주시고 다시 push 해 주세요!

2023-01-20 08:07 UTC, SeongJoon-K commented on wonkyung/app.js
> +require("dotenv").config();
```suggestion
require("dotenv").config();

const express = require("express");
const cors = require("cors");
const morgan = require("morgan");
const dotenv = require("dotenv");
```

2023-01-21 08:25 UTC, SeongJoon-K reviewed
db/schema.sql 파일은 해당 프로덕트의 데이터 구조를 보여주는 파일입니다. 이를 외부에 공개해서는 안됩니다. 그렇기 때문에 schema.sql 파일도 gitignore에서 관리해 주어야 합니다!

2023-01-21 08:25 UTC, SeongJoon-K commented on wonkyung/app.js
> +
의미없는 줄 바꿈은 지양해 주세요 ! 코드의 가독성을 저해합니다.
```suggestion
```

2023-01-21 08:25 UTC, SeongJoon-K commented on wonkyung/db/migrations/20230120054536_create_Users_table.sql
> +CREATE TABLE Users(
데이터베이스의 테이블 네이밍 컨벤션에 맞추어 table 명은 소문자로 작성해 주세요!
```Write SQL statements in the style of the MySQL Reference Manual
SQL keywords and reserved words: uppercase
Identifiers (table names, column names, etc.): lowercase
(출처: [dev.mysql.com](https://dev.mysql.com/doc/internals/en/coding-style.html))
```

2023-01-21 08:26 UTC, SeongJoon-K commented
원경님 고생하셨습니다 ! 리뷰 요청시 이전에 `수정 요청` 라벨은 지워주세요 !

2023-01-23 06:27 UTC, wkc28 commented
성준님 케어 감사합니다!!
근데 그 스키마파일을 보여주시면 안된다그랬는데 그럼 경로를 바꿔야 되는건가요?????? 나머지 한번에 몰아서 깃푸쉬 했습니다!!
머지 주시고 다음단계로 넘어가게 해주시면 감사합니다!!
2023년 1월 21일 (토) 오후 5:26, SEONGJOON KIM ***@***.***>님이 작성:

> 원경님 고생하셨습니다 ! 리뷰 요청시 이전에 수정 요청 라벨은 지워주세요 !
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wecode-bootcamp-korea/42-backend-westagram-3/pull/2#issuecomment-1399206746>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A457OKTOWEXMATU6O7QPM6LWTOMS5ANCNFSM6AAAAAAUAA3K5I>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-01-23 12:36 UTC, SeongJoon-K commented
안녕하세요 원경님 ! 아직 schema.sql 파일의 이력이 남아있습니다. 
gitignore에 등록하여도 남아있는 이유는 `.git`에 저장내역들이 담겨있는 캐시가 남아있기 때문입니다.
아래 명령어를 입력해 캐시를 삭제하시고 다시 push 해 주세요!
```
$ git rm -rf --cached [캐시를 삭제할 파일]
$ git rm -rf --cached . (모든 파일의 캐시를 삭제합니다)
```

2023-01-23 12:40 UTC, SeongJoon-K commented
원경님 !
`Q .41행 코드중 (server is listening on ${PORT} )); 부분의 ``과 ''의 차이를 명확히 알고싶습니다.`에 대한 답변을 드리자면, javascript (ES6) 문법 중 템플릿 문자열을 사용할 때 '``' 백틱을 사용합니다. 템플릿 문자열을 사용하게 되면 아래와 같이 선언한 변수를 문자열 안에 사용할 수 있게 됩니다 ! 
```
const name = "wk"

console.log(`${name}`);

// 결과 : wk
```
공식 문서를 참조해서 학습해보시면 좋을 거 같아 첨부합니다 ~
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Template_literals

2023-01-25 06:54 UTC, wkc28 commented
이젠..제대로 됫겟죠??

2023-01-25 08:37 UTC, sangwoong03 requested changes
고생하셨습니다 원경님!

리뷰를 천천히 읽어보시고, 이해가 안되는 부분은 커멘트 남겨주세요!

2023-01-25 08:37 UTC, sangwoong03 commented on wonkyung/.env.sample
> +node_modules/
해당 내용은 `.gitignore` 파일에서 관리되어야 할 파일입니다.
수정해주세요~!

2023-01-25 08:37 UTC, sangwoong03 commented on wonkyung/.env.sample
> +DATABASE_URL="mysql:/username:password@127.0.0.1:3306/DATABASE_name"
```suggestion
DATABASE_URL="rdbms:/username:password@host:port/database-name"
```

1. 우선 mysql 데이터베이스를 직접 명시하지 않아도 됩니다.
2. host와 port 역시 직접 명시하지 않아도 됩니다.
3. url 구조의 통일성을 위해 대소문자를 지켜주면 좋을 것 같습니다.

2023-01-25 08:37 UTC, sangwoong03 commented on wonkyung/.gitignore
> +you have to make your own schema file
해당 부분에 `.env.sample` 파일에 있는 내용 두가지가 추가되어야 할 것 같습니다.

추가로 db 폴더 내부의 `schema.sql` 파일이 github 상에서 공유되지 않도록 해당 파일에도 추가해주세요!
이미 추가가 되어있는데, `git rm --cached "file-path"` 명령어를 이용하여 삭제 후 다시 add ~ commit ~ push 해주세요!

```suggestion
.env
node_modules/
db/schema.sql
```

2023-01-25 08:37 UTC, sangwoong03 commented on wonkyung/app.js
> +  });
데이터베이스 Connection에 실패했을 경우 에러를 반환하도록 수정해주세요.

```suggestion
appDataSource.initialize()
  .then(() => {
      console.log("Data Source has been initialized!")
  })
  .catch(() => {
      console.log("Failed to connect to Database")
  });
```

2023-01-25 08:37 UTC, sangwoong03 commented on wonkyung/app.js
> +app.use(morgan(''));
공백으로 남겨두는 것 보다 어떤 옵션을 사용할 것인지 지정하여 로그를 좀 더 효율적으로 볼 수 있도록 수정해주세요!

2023-01-25 08:37 UTC, sangwoong03 commented on wonkyung/db/migrations/20230123062011_create_users_table.sql
> +);
미니과제) 다른 서비스를 이용하다 보면 회원가입을 할 때 유저의 아이디나 이메일 중복 체크를 했던 경험이 있으실 것입니다. 물론 클라이언트 혹은 서버 내부의 코드를 통해 중복 데이터를 거를 수 있습니다. 하지만 외적으로 주입되는 데이터에 대해 데이터베이스에서 직접 중복을 거를 수 있는 방법으로 해당 컬럼에 UNIQUE 제약 조건을 추가하는 방법이 있습니다.
제약 조건을 설정하는 코드를 추가해주세요!

2023-01-25 14:18 UTC, wkc28 commented on wonkyung/db/migrations/20230123062011_create_users_table.sql
> +);
과제2로 넘어가도 될까요?? 기다리면서 과제2도 대충 하긴했습니다.

2023-02-02 07:05 UTC, SeongJoon-K commented
원경님, 현재 PR은 초기환경세팅에 대한 것입니다. 해당 과제와는 별개로 다른 과제들이 올라와 있습니다.
브랜치를 분리해 개발을 하는 이유는 유지보수를 위함입니다. 초기환경세팅에 맞는 파일들만, push 해 주시고, 다른 파일들은
브랜치를 생성해서 다시 PR을 올려주세요

2023-02-23 06:13 UTC, closed without merging