[이한재] Assignment 3~8 Westagram API 구현.
wecode-bootcamp-korea/42-backend-westagram-3 pull request #6
Opened 2023-01-25 11:01 UTC by jayhanjaelee

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 데이터베이스 작업
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성

- Assignment 3 | Westagram Backend Project - 게시글 등록하기
- Assignment 4 | Westagram Backend Project - 전체 게시글 조회하기
- Assignment 5 | Westagram Backend Project - 유저의 게시글 조회하기
- Assignment 6 | Westagram Backend Project - 게시글 수정하기
- Assignment 7 | Westagram Backend Project - 게시글 삭제하기
- Assignment 8 | Westagram Backend Project - 좋아요 누르기

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)
- 

<br />

## :: 테스트 결과 이미지

1. Assignment 3 | Westagram Backend Project - 게시글 등록하기
![Screenshot 2023-01-25 at 7 39 04 PM](https://user-images.githubusercontent.com/122243107/214542265-39426504-39f4-4185-ac53-9de33ac0fddf.png)
![Screenshot 2023-01-25 at 7 39 27 PM](https://user-images.githubusercontent.com/122243107/214542459-c1bfe1cc-c1ad-48a1-a263-76aa90f41f37.png)

2. Assignment 4 | Westagram Backend Project - 전체 게시글 조회하기
![Screenshot 2023-01-25 at 7 42 23 PM](https://user-images.githubusercontent.com/122243107/214542833-1b674075-11ec-4238-9097-a703dbdd73ae.png)

3. Assignment 5 | Westagram Backend Project - 유저의 게시글 조회하기
![Screenshot 2023-01-25 at 7 42 23 PM](https://user-images.githubusercontent.com/122243107/214542966-f88b122d-cb20-4387-8360-c6b6a7bc510b.png)

4. Assignment 6 | Westagram Backend Project - 게시글 수정하기
![Screenshot 2023-01-25 at 7 44 19 PM](https://user-images.githubusercontent.com/122243107/214543301-046b13df-87e7-4e67-8c0b-421d7a7a2756.png)
![Screenshot 2023-01-25 at 7 44 05 PM](https://user-images.githubusercontent.com/122243107/214543233-eee75635-e407-48d1-800c-a5eeff3dbd1f.png)

5. Assignment 7 | Westagram Backend Project - 게시글 삭제하기
![Screenshot 2023-01-25 at 7 46 33 PM](https://user-images.githubusercontent.com/122243107/214543759-c5ffc25b-92b2-453c-a74d-e28af
![Screenshot 2023-01-25 at 7 46 45 PM](https://user-images.githubusercontent.com/122243107/214543779-88c34103-3a7f-4941-9e18-10b899a2e7b3.png)
3d631f9.png)

6. Assignment 8 | Westagram Backend Project - 좋아요 누르기
![Screenshot 2023-01-25 at 7 48 19 PM](https://user-images.githubusercontent.com/122243107/214544079-9d7cc728-e59d-4da5-ab47-3d158ad42041.png)
![Screenshot 2023-01-25 at 7 49 13 PM](https://user-images.githubusercontent.com/122243107/214544265-5dcf2ad1-3f7c-47d9-94eb-c29dbfb0f757.png)

## :: 기타 질문 및 특이 사항
- 이전 과제에서 작성한 회원가입 API 에 대해서 then, catch 구문을 사용하였었는데 async await 가 같은 역할을 하는 것 같아서 변경하였습니다. 
Promise 객체에 대해서 then catch 구문을 이용하는 것과 async await 를 사용하는 것은 같은 역할을 한다고 봐도 무방할까요?

- 개인적으로 db 초기화 하고 샘플 데이터를 넣기 위해서 init_db.py 파일을 추가하였습니다.

- likes 테이블에 Unique 제약조건을 (user_id, post_id) 한 쌍에 대하여 추가하였습니다. 이렇게 작업한 이유는 어떤 한 유저가 같은 게시물에대하여 여러번의 좋아요를 누를때마다 데이터가 추가되는 것은 불필요하다고 생각했습니다.

- 과제 2, 3 회원가입과 게시글 등록하기 API 에 대해서 

```js 
return res.status(202).json({ message: 'userNotCreated' })
```

과 같이 정상적으로 데이터 추가가 안되었을 경우에 대해서 response status code 를 어떤걸 주어야 적절할지 잘 모르겠습니다.
클라이언트가 요청은 적절하게 했지만 이미 추가된 데이터에 대하여 동일한 데이터를 추가하려고 했을때 어떤 status code 를 주는것이 적절할까요?

2023-01-26 01:47 UTC, SeongJoon-K commented on hanjaelee/app.js
> +    ) VALUES (?, ?, ?);`
```suggestion
  const rawQuery =`
    INSERT INTO posts (
      title,
      content,
      user_id
    ) VALUES (?, ?, ?);`
```

2023-01-26 01:47 UTC, SeongJoon-K commented on hanjaelee/app.js
> +  `
```suggestion
  let rawQuery = `
    UPDATE posts
    SET content = ?
    WHERE id = ? AND user_id = ?;`
```

2023-01-26 01:47 UTC, SeongJoon-K commented on hanjaelee/app.js
> +  `
```suggestion
  const rawQuery = `
    INSERT INTO likes (
        user_id, 
        post_id
    ) VALUES (?, ?);`
```

2023-01-26 02:11 UTC, jayhanjaelee commented
rawQuery 스타일 수정하였습니다.

2023-01-26 02:50 UTC, sangwoong03 requested changes
한재님 상당히 코드가 깔끔하네요👍
작성해주시느라 고생하셨습니다. 리뷰 확인 후 이해 안되는 부분은 커멘트 부탁드릴게요 ㅎㅎ

2023-01-26 02:50 UTC, sangwoong03 commented on hanjaelee/app.js
> +})
엄청 깔끔하네요 한재님 👍

- 코드 라인을 조금 구분하면 구조 파악에 더 용이할 것 같습니다!!
- 로그에서 에러를 파악하고 디버깅 할 수 있도록 `console.error()` 구문을 추가해주면 좋을 것 같습니다.

```suggestion
  try {
    const rawData = await database.query(rawQuery, [name, email, profileImage, password])
    
    if (rawData['affectedRows']) {
      return res.status(201).json({ message: 'userCreated' })
    }
    
    return res.status(202).json({ message: 'userNotCreated' })
  } catch (error) {
    console.error("Failed to Signup", error)
    return res.status(400).json({ message: error.sqlMessage })
  }
})
```

2023-01-26 02:50 UTC, sangwoong03 commented on hanjaelee/app.js
> +  }
데이터 받아오는 부분도 `try { ... }` 구문 안에 넣어도 될 것 같습니다.
이 부분도 마찬가지로 포매팅 한번 수정해서 가독성 높이고 에러 디버깅 코드 추가하면 좋을 것 같습니다.

```suggestion
  try {
  const { title, content, userId } = req.body

  const rawQuery =
    `
    INSERT INTO posts (
      title,
      content,
      user_id
    ) VALUES (?, ?, ?);`

    const rawData = await database.query(rawQuery, [title, content, userId])
    
    if (rawData['affectedRows']) {
      return res.status(201).json({ message: 'postCreated' })
    }
    
    return res.status(202).json({ message: 'postnotcreated' })
  } catch (error) {
    console.error("Failed to Posting", error)
    return res.status(400).json({ message: error.sqlMessage })
  }
```

2023-01-26 02:50 UTC, sangwoong03 commented on hanjaelee/app.js
> +app.get('/posts', async (req, res) => {
엔드포인트가 post Method 일 떄 (바로 위의 API)는 `/post`로 되어 있는데 통일이 되면 좋을 것 같아요!
클라이언트는 GET 또는 POST로 Method만 수정하면 될 것 같습니다.

이는 차후 레이어드 패턴을 적용 시 Router 분리를 하면서 왜 통일하는 것이 좋은지 감이 잡히실 것 같습니다.

2023-01-26 02:50 UTC, sangwoong03 commented on hanjaelee/app.js
> +      res.status(200).json(result)
await 키워드로 비동기 함수를 처리하고 있기 때문에 두번째 인자로 받는 콜백 함수 부분을 작성해줄 필요가 없어보입니다.
```suggestion
    const [result] = await database.query(rawQuery)
    
     return res.status(200).json(result)
```

2023-01-26 02:50 UTC, sangwoong03 commented on hanjaelee/app.js
> +    GROUP BY u.id;
쿼리 포매팅 수정하면 좋을 것 같습니다!

```suggestion
    SELECT
      u.id AS userId,
      u.profile_image AS userProfileImage,
      JSON_ARRAYAGG(
          JSON_OBJECT(
              'postingId', p.id,
              'postingImageUrl', p.image_url,
              'postingContent', p.content)) AS posting
    FROM posts AS p
    INNER JOIN users AS u
    ON p.user_id = u.id WHERE u.id = ?
    GROUP BY u.id;
```

2023-01-26 02:50 UTC, sangwoong03 commented on hanjaelee/app.js
> +      return res.status(200).json({ data: rows })
해당 부분도 await 키워드를 사용하기 때문에 쿼리에 대한 결과값을 바로 변수에 할당에서 응답 data로 보내면 될 것 같습니다.

```suggestion
    const [result] = await database.query(rawQuery, (err, rows) => {
      return res.status(200).json({ data: result })
```

2023-01-26 02:50 UTC, sangwoong03 commented on hanjaelee/app.js
> +    GROUP BY u.id;`
- 해당 부분도 `try { ... }` 구문 안에 넣어도 될 것 같아요.
-`rawQuery`에 대한 포매팅도 수정하면 가독성이 더 좋아질 것 같습니다.
- `?` 매핑을 사용할 수 있게 수정해주세요!

```suggestion
  const { userId } = req.params
  const rawQuery = `
    SELECT
      u.id AS userId,
      u.profile_image AS userProfileImage,
      JSON_ARRAYAGG(
        JSON_OBJECT(
          'postingId', p.id,
          'postingImageUrl', p.image_url,
          'postingContent', p.content
          )
      ) AS postings
    FROM posts AS p
    INNER JOIN users AS u
    ON p.user_id = u.id WHERE u.id = ?
    GROUP BY u.id;`
```

2023-01-26 02:50 UTC, sangwoong03 commented on hanjaelee/app.js
> +})
한재님 아래 코드로도 실행되는지 확인해주실 수 있나요?
```suggestion
app.patch('/post', async (req, res) => {
  try {
    const { postId, userId, postContent } = req.body
    let rawQuery = `
      UPDATE posts
      SET content = ?
      WHERE id = ? AND user_id = ?;`

    const rawData = await database.query(rawQuery, [postContent, postId, userId])
    
    if ( rawData['affectedRows'] ) {
      rawQuery = `
      SELECT
        u.id AS userId,
        u.name AS userName,
        p.id AS postingId,
        p.title AS postingTitle,
        p.content AS postingContent FROM posts AS p
      INNER JOIN users AS u
      ON p.user_id = u.id
      WHERE u.id = ? AND p.id = ?
      LIMIT 1;`

      const [result] = await database.query(rawQuery)
      return res.status(200).json({ data : result })
    }
  }
  catch (error) {
    console.error('Failed to update user posting', error)
    return res.status(400).json({ message: error.sqlMessage })
  }
})
```

2023-01-26 02:50 UTC, sangwoong03 commented on hanjaelee/app.js
> +// 과제 7 게시글 삭제하기
과제 7, 8부분도 위의 리뷰 반영해서 수정해보신 후 제가 다시 확인해보겠습니다 😀

2023-01-26 03:07 UTC, jayhanjaelee commented on hanjaelee/app.js
> +app.get('/posts', async (req, res) => {
엔드포인트를 /posts 에서 /post 로 통일하라는 말씀이실까요?
Method 는 게시물 가져오는 거라서 get 으로 유지하면 되겠죠?

2023-01-26 03:48 UTC, jayhanjaelee commented on hanjaelee/app.js
> +      res.status(200).json(result)
멘토님 피드백 주신대로 수정하면 result 에 row 가 하나만 들어간 구조가 되더라구요
이부분은 모든 게시물 가져오는 부분인데.. 추가 피드백 부탁드립니다!

2023-01-26 04:19 UTC, jayhanjaelee commented on hanjaelee/app.js
> +      res.status(200).json(result)
데이터가 여러개가 와야 하는데 피드백 주신대로 수정하면 데이터가 한개만 들어옵니다!
추가 피드백 부탁드리겠습니다!

2023-01-26 04:32 UTC, jayhanjaelee commented on hanjaelee/app.js
> +})
실행 됩니다 수정하겠습니다

2023-01-26 04:50 UTC, jayhanjaelee commented
@SeongJoon-K 과제 4 에 모든 게시물 가져오기 부분에서 피드백 주신 

   `await database.query(rawQuery, (err, rows) => {})`
      
   를
   
   `const [result] = await database.query(rawQuery)`
   
  와 같이 수정하라고 하셨는데 이렇게 수정하게되면 
 수정전에는 배열에 객체가 여러개가 들어가는 구조인데
 수정후에는 배열에 객체가 하나만 들어가게 됩니다
 추가 피드백 부탁드리겠습니다!
 
 나머지 피드백 반영해서 수정했는데 혹시 틀린 부분 있거나 보완해야 할 부분있으면 피드백 부탁드리겠습니다

2023-01-26 09:54 UTC, sangwoong03 commented on hanjaelee/app.js
> +app.get('/posts', async (req, res) => {
네 맞습니다! 메서드는 다르지만 posts 혹은 post 라는 동일한 리소스를 적어주는 것이 좀 더 좋을 것 같습니다!
이는 또한 이후 레이어드 패턴에서는 해당 posts에 대한 라우팅을 통합으로 관리할 수 있어서 더 효율적일 것입니다!!

```javascript
// postRouter.js
router.get('/', ...)
router.post('/'. ...)

...
...
// routes/index.js
router.use('/posts', postRouter);
```

2023-01-26 09:54 UTC, sangwoong03 commented
> @sangwoong03 과제 4 에 모든 게시물 가져오기 부분에서 피드백 주신
> 
> `await database.query(rawQuery, (err, rows) => {})`
> 
> 를
> 
> `const [result] = await database.query(rawQuery)`
> 
> 와 같이 수정하라고 하셨는데 이렇게 수정하게되면 수정전에는 배열에 객체가 여러개가 들어가는 구조인데 수정후에는 배열에 객체가 하나만 들어가게 됩니다 추가 피드백 부탁드리겠습니다!
> 
> 나머지 피드백 반영해서 수정했는데 혹시 틀린 부분 있거나 보완해야 할 부분있으면 피드백 부탁드리겠습니다

해당 부분 `[result]`를 result로 수정해서 진행해보시겠어요!?

2023-01-26 10:07 UTC, sangwoong03 requested changes

2023-01-26 10:07 UTC, sangwoong03 commented on hanjaelee/app.js
> +      const [result] = await database.query(rawQuery, [userId, postId])
이 부분을 아래와 같이 수정 후 결과 확인 부탁드려요!
```suggestion
      const result = await database.query(rawQuery, [userId, postId])
```

2023-01-26 10:07 UTC, sangwoong03 commented on hanjaelee/app.js
> +// Client 로 부터 JSON 형식이 잘못되었을 경우 처리하는 middleware
한재님! 해당 주석으로 코드를 설명하려는 의도는 너무 좋습니다!
다만, 코드를 수정했을 경우 주석까지 수정해야하는 소요가 발생할 것입니다.
지금은 간단한 API를 구현하고 있기 때문에 코드를 설명하는 주석이 길지 않지만, 경험하셨듯 실제 프로젝트를 할 땐 그렇지 못하는 경우가 많아 문서화로 대체하는 경우가 있을 것입니다.

하지만 위코드에서는 코드로서 설명할 수 있고, 그것이 안된다면 문서화로 대체하는 것을 가이드하고 있으니 마무리 단계에서 주석을 모두 삭제해주면 좋을 것 같습니다!

```suggestion
```

2023-01-26 10:33 UTC, jayhanjaelee commented on hanjaelee/app.js
> +      const [result] = await database.query(rawQuery, [userId, postId])
결과 정상적으로 나옵니다 배열로 결과 값을 넣으면 값이 하나만 들어가고  피드백 주신 코드로 하면 전부 들어가네요
원래 sql 문에서 의도한 결과값이 데이터가 이미 배열이라서 그런걸까요? 무슨 차이인지 설명 부탁드립니다.

2023-01-27 01:07 UTC, SeongJoon-K approved these changes

2023-01-27 01:07 UTC, SeongJoon-K commented on hanjaelee/app.js
> +      const [result] = await database.query(rawQuery, [userId, postId])
`const [result]`로 결과를 받게 되었을 때, 구조분해할당이 되어 쿼리문에서 하나의 값만 할당되게 됩니다! 그래서 모든 게시물의 값을 가져오기 위해서 배열로 가져오는 게 아닌, 변수로써 가져와야 하는 것입니다 ~

2023-01-27 01:07 UTC, merged